apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: e-commerce
spec:
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP